data: EuroSAT

hp: 
  training_params: 
    num_epoch: 100
    batch_size: 1024
  model_params: 
    nz: 16
  optim_params: 
    lr: 0.001
    betas: [0.9, 0.999]

save_dir: ../Result/hyper_scan/EuroSAT