training_params:
  data: EuroSAT
  n_components: 16
  batch_size: 128
  num_epochs: 30
  loss_type: [BCE_loss, accuracy]  

model_params:
  num_wires: 8
  ver: U_SO4
  Embedding: Angular
  trans_inv: True

optim_params : 
  learning_rate: 0.01
  b1: 0.9
  b2: 0.999

logging_params: 
  save_dir: ../Result/binary_scan2/EuroSAT/U_SO4
